### PR TITLE
chore: improve development config

### PR DESCRIPTION
**Pull request by swiizyy**
⚠️  BREAKING CHANGE: 
Don't forget to add the `NPM PUBLISH TOKEN` key in the github environment variables

### CODE REVIEW

**Comment by Swiizyy** [comment]
LGTM 🚀

**Comment by swiizyy** [comment]
LGTM 	🚀

**Comment by fearandesire** [comment]
Hey, thanks for finishing the PR!

In [this commit](https://github.com/fearandesire/saph-convert/pull/2/commits/08642f0b6e4a93b2d2ecac78947bee7e5a8f2d41), do you mind correcting the typo for the folder `problemMastchers` to -> `problemMatchers`?

**Comment by swiizyy** [comment]
⚠️  When merging a branch use `Squash and merge` rather than the default merge.
ℹ️  This will compress the PR into 1 single commit and will be more pleasant to manage

**Comment by fearandesire** [comment]
Thank you my friend!

**Pull request merged**
